INSERT INTO `offices`(`code`, `name`, `address`, `responsibility_center_code`, `contact_no`,`created_at`, `updated_at`) VALUES
('PGSO', 'Provincial General Services Office','Oroquieta City', NULL, Null, now(), now()),
('AMORAP', 'Asenso Misamis Occidental Resort and Aquamarine Park','Hoyohoy, Tangub City', NULL, Null, now(), now()),
('BAC', 'Bids and Awards Committee','3rd Floor, Capitol Annex Building, Oroquieta City', NULL, Null, now(), now()),
('CDH', 'Calamba District Hospital','Calamba', NULL, Null, now(), now()),
('DA', 'Provincial Agriculture Office','Oroquieta City', NULL, Null, now(), now()),
('DMDTMH', 'Doña Maria D. Tan Memorial Hospital','Tangub City, Misamis Occidental', NULL, Null, now(), now()),
('AGG', 'Asenso Global Gardens','Hoyohoy, Tangub City, Misamis Occidental', NULL, Null, now(), now()),
('IPHO', 'Integrated Provincial Health Office','Oroquieta City',NULL,NULL,now(),now()),
('MOPRJ', 'Misamis Occidental Provincial Reformatory Jail','Lower Lamac, Oroquieta City', NULL, Null, now(), now()),
('JMCH', 'Jimenez Medicare Community Hospital','Jimenez, Misamis Occidental', NULL, Null, now(), now()),
('MODTRC', 'Misamis Occidental Drug Treatment and Rehabilitation Center','Oroquieta City', NULL, Null, now(), now()),
('MOEDRC', 'Misamis Occidental Enterprise Development & Research Center','Oroquieta City', NULL, Null, now(), now()),
('MOPAC', 'Misamis Occidental Provincial Athletic Complex','Oroquieta City', NULL, Null, now(), now()),
('MOPH', 'Misamis Occidental Provincial Hospital','Oroquieta City', NULL, Null, now(), now()),
('MOPLIC', 'Misamis Occidental Provincial Library and Information Center','Oroquieta City', NULL, Null, now(), now()),
('OLS', 'Office of the Legal Services','Oroquieta City', NULL, Null, now(), now()),
('OPPDC', 'Office of the Provincial Planning and Development Coordinator','Oroquieta City',NULL, Null, now(), now()),
('OPTACA', 'Office of the Provincial Tourism, Arts and Cultural Affairs','Oroquieta City',NULL, Null, now(), now()),
('PACCO', 'Provincial Accountant''s Office','Oroquieta City',NULL, Null, now(), now()),
('PASSO', 'Provincial Assesor''s Office','Oroquieta City',NULL, Null, now(), now()),
('PBO', 'Provincial Budget Office','Oroquieta City',NULL, Null, now(), now()),
('PCOOP', 'Provincial Cooperative Office','Oroquieta City', NULL, Null, now(), now()),
('PDAO', 'Person with Disability Affairs Office','Oroquieta City', NULL, Null, now(), now()),
('PDRRMO', 'Provincial Disaster Risk Reduction Management Office','Oroquieta City', NULL, Null, now(), now()),
('OPEE', 'Office of the Provincial Economic Enterprise','Oroquieta City', NULL, Null, now(), now()),
('PEO', 'Provincial Engineers Office','Oroquieta City', NULL, Null, now(), now()),
('PESO', 'Provincial Employment Services Office','Oroquieta City', NULL, Null, now(), now()),
('PG-ENRO', 'Provincial Environment and Natural Resources Office','Oroquieta City', NULL, Null, now(), now()),
('PGADO', 'Provincial Gender and Development Office','Oroquieta City', NULL, Null, now(), now()),
('PGO', 'Provincial Governor''s Office','Oroquieta City', NULL, Null, now(), now()),
('PHRMO', 'Provincial Human Resource Management and Development Office','Oroquieta City',NULL, Null, now(), now()),
('PIAO', 'Provincial Internal Audit Office','Oroquieta City',NULL, Null, now(), now()),
('PNAO', 'Provincial Nutrition Action Office','Oroquieta City',NULL, Null, now(), now()),
('PSWDO', 'Provincial Social Welfare and Development Office','Oroquieta City',NULL, Null, now(), now()),
('PTO', 'Provincial Treasurer''s Office','Oroquieta City',NULL, Null, now(), now()),
('PVO', 'Provincial Veterinary Office','Oroquieta City',NULL, Null, now(), now()),
('SP', 'Sangguniang Panlalawigan','Oroquieta City',NULL, Null, now(), now()),
('OSSP', 'Office of the Secretary to the Sangguniang Panlalawigan','Oroquieta City',NULL, Null, now(), now()),
('TMH', 'Tudela Municipal Hospital','Tudela, Misamis Occidental',NULL, Null, now(), now());
