INSERT INTO `offices`(`code`, `name`, `address`, `head_of_office`, `position`, `contact_no`,`created_at`, `updated_at`) VALUES 
('AMORAP', 'Asenso Misamis Occidental Resort and Aquamarine Park','Hoyohoy, Tangub City',NULL,NULL,NULL,now(),now()),
('BAC', 'Bids and Awards Committee','3rd Floor, Capitol Annex Building, Oroquieta City','Blaise L. Roa','BAC Secretariat',NULL,now(),now()),
('DA', 'Provincial Agriculture Office','Oroquieta City','Dennis C. Leopoldo','Provincial Agriculturist',NULL,now(),now()),
('DMDTMH', 'Doña Maria D. Tan Memorial Hospital','Tangub City, Misamis Occidental','Emma A. Pineda, M.D., MPA','Chief of Hospital I',NULL,now(),now()),
('AGG', 'Asenso Global Gardens','Hoyohoy, Tangub City, Misamis Occidental',NULL,Null,NULL,now(),now()),
('IPHO', 'Integrated Provincial Health Office','Oroquieta City','Dr. Holly Tago',NULL,NULL,now(),now()),
('MOPRJ', 'Misamis Occidental Provincial Reformatory Jail','Lower Lamac, Oroquieta City','Stephen Sean M. Daral','Provincial Warden',NULL,now(),now()),
('JMCH', 'Jimenez Medicare Community Hospital','Jimenez, Misamis Occidental','Bryan Aizzer T. Adona','Chief of Hospital',NULL,now(),now()),
('MODTRC', 'Misamis Occidental Drug Treatment and Rehabilitation Center','Oroquieta City','Frods A. Kaamiño','Technical Head',NULL,now(),now()),
('MOEDRC', 'Misamis Occidental Enterprise Development & Research Center','Oroquieta City','Lorelie Salud U. Cagas',NULL,NULL,now(),now()),
('MOPAC', 'Misamis Occidental Provincial Athletic Complex','Oroquieta City','Cristy O. Saplot',NULL,NULL,now(),now()),
('MOPH', 'Misamis Occidental Provincial Hospital','Oroquieta City','Benecio L. Adona, MD, FICS, FPSMS',NULL,NULL,now(),now()),
('MOPLIC', 'Misamis Occidental Provincial Library and Information Center','Oroquieta City','Rogelyn C. Serino','MOPLIC Officer',NULL,now(),now()),
('OLS', 'Office of the Legal Services','Oroquieta City','Atty. Peter Elfred A. Lasmarias','Legal Officer',NULL,now(),now()),
('OPPDC', 'Office of the Provincial Planning and Development Coordinator','Oroquieta City','William I. Valles, Jr.','Provincial Coordinator',NULL,now(),now()),
('OPTACA', 'Office of the Provincial Tourism, Arts and Cultural Affairs','Oroquieta City','Cristy O. Saplot','Provincial Tourism Coordinator',NULL,now(),now()),
('PACCO', 'Provincial Accountant''s Office','Oroquieta City','Merieta C. Acosta, CPA','Provincial Accountant',NULL,now(),now()),
('PASSO', 'Provincial Assesor''s Office','Oroquieta City','Nepthaly Leo L. Adlaon','Provincial Assessor',NULL,now(),now()),
('PBO', 'Provincial Budget Office','Oroquieta City','Sarah D. Gamurot','Provincial Budget Officer',NULL,now(),now()),
('PCOOP', 'Provincial Cooperative Office','Oroquieta City','Sarah D. Gamurot','Provinical Budget Officer',NULL,now(),now()),
('PDAO', 'Person with Disability Affairs Office','Oroquieta City',NULL,NULL,NULL,now(),now()),
('PDRRMO', 'Provincial Disaster Risk Reduction Management Office','Oroquieta City','Villanueva',NULL,NULL,now(),now()),
('OPEE', 'Office of the Provincial Economic Enterprise','Oroquieta City','Jonathan T. Callanta','PGDH-PPEO',NULL,now(),now()),
('PEO', 'Provincial Engineers Office','Oroquieta City','Engr. Theresita C. Maisog','Provincial Engineer',NULL,now(),now()),
('PESO', 'Provincial Employment Services Office','Oroquieta City','Engr. Theresita C. Maisog','Provincial Engineer',NULL,now(),now()),
('PG-ENRO', 'Provincial Environment and Natural Resources Office','Oroquieta City','Meriam M. Betito','Sr. Environmental Management Specialist',NULL,now(),now()),
('PGADO', 'Provincial Gender and Development Office','Oroquieta City','Maribel V. Gonzales','PGDH-PGADO',NULL,now(),now()),
('PGO', 'Provincial Governor''s Office','Oroquieta City','Atty. Henry S. Oaminal','Provincial Governor',NULL,now(),now()),
('PGSO', 'Provincial General Services Office','Oroquieta City','Daisy Talictic','OIC-PGSO Officer',NULL,now(),now()),
('PHRMO', 'Provincial Human Resource Management and Development Office','Oroquieta City','Rone L. Nierva','OIC-PHRMO',NULL,now(),now()),
('PIAO', 'Provincial Internal Audit Office','Oroquieta City','Rone L. Nierva','OIC-PIA',NULL,now(),now()),
('PNAO', 'Provincial Nutrition Action Office','Oroquieta City','Marichu G. Tijiing','PNAO Officer',NULL,now(),now()),
('PSWDO', 'Provincial Social Welfare and Development Office','Oroquieta City','Lorellie J. Yee','PSWD Officer',NULL,now(),now()),
('PTO', 'Provincial Treasurer''s Office','Oroquieta City','Elma P. Burlat','Provincial Treasurer',NULL,now(),now()),
('PVO', 'Provincial Veterinary Office','Oroquieta City','Dr. Michael Joseph S. Sanciangco, DVM','Provincial Veterinarian',NULL,now(),now()),
('SP', 'Sangguniang Panlalawigan','Oroquieta City','Rowena L. Gutierrez','Provincal Vice Governor',NULL,now(),now()),
('TMC', 'Tudela Municipal Hospital','Tudela, Misamis Occidental','Dr. Rommer V. Destura','OIC-Chief of Hospital',NULL,now(),now());