INSERT INTO `uoms` (`name`,`description`,`created_at`, `updated_at`) VALUES
('amp','Ampule',now(),now()),
('vial','Vial',now(),now()),
('bot','Bottle',now(),now()),
('cap','Capsule',now(),now()),
('tab','Tablet',now(),now()),
('pc','Piece',now(),now()),
('pack','Pack',now(),now()),
('supp','Suppository',now(),now()),
('tube','Tube',now(),now()),
('ream','Ream',now(),now()),
('can','Can',now(),now()),
('box','Box',now(),now()),
('unit','Unit',now(),now()),
('set','Set',now(),now()),
('cart','Cartridge',now(),now()),
('kit','Kit',now(),now()),
('pad','Pad',now(),now()),
('sac','Sachet',now(),now()),
('bag','Bag',now(),now()),
('gal','Gallon',now(),now()),
('roll','Roll',now(),now());

